swagger: "2.0"
info:
  version: 1.0.0
  title: BHuman api documentation
  contact:
    email: admin@bhuman.ai
host: api.bhuman.ai
basePath: /api
schemes:
  - "https"
securityDefinitions:
  basicAuth:
    type: basic
tags:
  - name: video
  - name: store
  - name: workspace
paths:
  /ai_studio/pipeline3:
    post:
      summary: Send video generation request
      description: Send ai based video generation request with given parameters
      operationId: videoGeneration
      security:
        - basicAuth: []
      tags:
        - video
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: VideoGenerateResponse
          schema:
            $ref: "#/definitions/VideoGenerateRequest"
      responses:
        "200":
          description: Video generation request successfully sent.
          schema:
            $ref: "#/definitions/VideoGenerateResponse"
        "400":
          description: Bad request
  /ai_studio/video_instance:
    get:
      summary: Get workspace video instances
      description: Get workspace video instances for user
      operationId: getVideoInstance
      security:
        - basicAuth: []
      parameters:
        - in: query
          name: workspace_id
          type: string
          required: true
      tags:
        - video
      produces:
        - application/json
      responses:
        "200":
          description: Get video instances successfully.
          schema:
            $ref: "#/definitions/VideoInstanceResponse"
        "400":
          description: Bad request
  /store/product:
    get:
      summary: Get template videos
      description: Get all template videos linked to your users
      operationId: getTemplates
      security:
        - basicAuth: []
      tags:
        - store
      produces:
        - application/json
      responses:
        "200":
          description: Get template videos successfully.
          schema:
            $ref: "#/definitions/GetTemplatesResponse"
        "400":
          description: Bad request
  /store/product/use:
    post:
      summary: Use template video
      description: Use template video
      operationId: useTemplate
      security:
        - basicAuth: []
      tags:
        - store
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: UseTemplateVideo
          schema:
            $ref: "#/definitions/UseTemplateVideoRequest"
      responses:
        "200":
          description: Template video succesfully used.
          schema:
            $ref: "#/definitions/UseProductResponse"
        "400":
          description: Bad request
  /workspace:
    get:
      summary: Get workspace data
      description: Get workspace data
      operationId: getWorkspace
      security:
        - basicAuth: []
      tags:
        - workspace
      produces:
        - application/json
      responses:
        "200":
          description: Get workspace successfully.
          schema:
            $ref: "#/definitions/GetWorkspaceResponse"
        "400":
          description: Bad request
definitions:
  VideoGenerateRequest:
    type: object
    properties:
      variables:
        type: array
        items:
          type: string
        description: Variables you want to replace
        example: ["name", "country", "city"]
      names:
        type: array
        items:
          type: array
          items:
            type: string
        description: Names you want to replace with variables
        example: [["Kartal", "Türkiye", "Istanbul"], ["Don", "USA", "New york"]]
      video_instance_id:
        type: string
        description: Video instance id of video. Could be template video or your personal video
        example: "0cd9070c-7699-4c42-ac65-8fc1c4d9a9b1"
      callback_url:
        type: string
        example: "https://webhook.site/XYZ"
        description: You will get the generation result with callback url. There will be an id parameter as a querystring in the callback url. This parameter corresponds to the id in the response returned from the pipeline endpoint.
  VideoGenerateResponse:
    type: object
    properties:
      result:
        type: array
        items:
          type: string
          description: Video id
      code:
        type: integer
        format: uint64
        example: 200
        description: http status code
  GetTemplatesResponse:
    type: object
    properties:
      result:
        type: array
        items:
          $ref: "#/definitions/TemplateResponse"
      code:
        type: number
        format: uint64
  TemplateResponse:
    type: object
    properties:
      id:
        type: string
        description: Use this id to use template
      name:
        type: string
      video_url:
        type: string
      image_url:
        type: string
      thumbnail:
        type: string
      actor_id:
        type: string
  UseTemplateVideoRequest:
    type: object
    properties:
      id:
        type: string
        description: Template id taken from template endpoint
      workspace_id:
        type: string
      folder_id:
        type: string
    required:
      - id
      - workspace_id
      - folder_id
  UseProductResponse:
    type: object
    properties:
      result:
        type: array
        items:
          $ref: "#/definitions/UseProductResult"
      code:
        type: number
        format: uint64
  UseProductResult:
    type: object
    properties:
      video_instance_id:
        type: string
      folder_id:
        type: string
  GetWorkspaceResponse:
    type: object
    properties:
      result:
        type: array
        items:
          $ref: "#/definitions/WorkspaceResponse"
      code:
        type: number
        format: uint64
  WorkspaceResponse:
    type: object
    properties:
      workspace_id:
        type: string
      description:
        type: string
  VideoInstanceResponse:
    type: object
    properties:
      result:
        type: array
        items:
          $ref: "#/definitions/VideoInstance"
      code:
        type: number
        format: uint64
  VideoInstance:
    type: object
    properties:
      id:
        type: string
      folder_id:
        type: string
      name:
        type: string
